{
  "formatVersion": "1.1",
  "component": {
    "group": "top.girlkisser",
    "module": "Lazuli",
    "version": "1.0.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Lazuli-1.0.0+1.21.1.jar",
          "url": "Lazuli-1.0.0+1.21.1.jar",
          "size": 124973,
          "sha512": "ef41a681ecccd37f9aa60b6d17486d7c0fe65833ee22da44ecc18221bd71633d8dcd3b8c1722baf3d6e8dfba2ce388da0c49f5dd7be3626db25be8ddc231acc4",
          "sha256": "54074570d86d10115df27297b972fa87316b0c8f092a3a75efebebabfa9b0151",
          "sha1": "e4d07f54909e71652908af51bd2d00d835de6bd0",
          "md5": "eb16acb7b7edaae22571e8bfda832cc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.18+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "Lazuli-1.0.0+1.21.1.jar",
          "url": "Lazuli-1.0.0+1.21.1.jar",
          "size": 124973,
          "sha512": "ef41a681ecccd37f9aa60b6d17486d7c0fe65833ee22da44ecc18221bd71633d8dcd3b8c1722baf3d6e8dfba2ce388da0c49f5dd7be3626db25be8ddc231acc4",
          "sha256": "54074570d86d10115df27297b972fa87316b0c8f092a3a75efebebabfa9b0151",
          "sha1": "e4d07f54909e71652908af51bd2d00d835de6bd0",
          "md5": "eb16acb7b7edaae22571e8bfda832cc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Lazuli-1.0.0+1.21.1-sources.jar",
          "url": "Lazuli-1.0.0+1.21.1-sources.jar",
          "size": 67579,
          "sha512": "b435e8a9d6f1cc2f9c87d0dea23964b15baed1f204e8a6a0e0a4582ab200dbac3ae34a35a2363148807d97f7eb658d9260630bd0eb7ee4cc0f674fcc55a2fef8",
          "sha256": "88868af4b2584f579ad26fc3308ab12c8edb0f93950d5fa137adce2bdcee5abc",
          "sha1": "d1372639b3576585d2f1e75132f130b3339797f4",
          "md5": "6b2aa2d6ff042ea34e9560c7fe0c5ed6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Lazuli-1.0.0+1.21.1-javadoc.jar",
          "url": "Lazuli-1.0.0+1.21.1-javadoc.jar",
          "size": 426509,
          "sha512": "65864d3fabe446b8aba7e6971eb3542e1aa89831082df4ec82efb79602e5e9aa04dd171531fe863be1b80c77c2698f4b46f73096c929b2c4ffcd6805bfc4f4f7",
          "sha256": "7f5699c3bb415ec37abdd1b0a0823f2fc0d65635cfe6aa1e853d986df35d1abc",
          "sha1": "dbb6ae1734f98adf69276d95216dc9e7e3f5c76d",
          "md5": "8224881996bd94e0ec7b757e6d6ac358"
        }
      ]
    }
  ]
}
